services:
  # ==========================
  # Backend
  # ==========================
  - type: web
    name: rag-knowledge-backend
    env: python
    region: oregon
    plan: starter

    rootDir: backend
    branch: main

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: GROQ_API_KEY
        sync: false

      - key: FRONTEND_URLS
        value: "*"

      - key: PYTHONUNBUFFERED
        value: "1"

      - key: TORCH_CPU_ONLY
        value: "1"

    autoDeploy: true


  # ==========================
  # Frontend
  # ==========================
  - type: web
    name: rag-knowledge-frontend
    env: static
    plan: starter

    rootDir: frontend
    branch: main

    buildCommand: npm install && npm run build
    staticPublishPath: dist

    envVars:
      - key: VITE_API_URL
        sync: false

    autoDeploy: true